name = "sst-mining-platform"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# Binding para Cloudflare AI
[ai]
binding = "AI"

# Binding para Cloudflare D1
[[d1_databases]]
binding = "DB"
database_name = "sst_db"
database_id = "90b26fa8-4121-4c29-b78c-a53dadea658d"

pages_build_output_dir = "SST_Dashboard"
